### ISSUE TITLE
Australian Weather Prediction 

### ISSUE THREAD

**Issue by Sansgupta25** [Git-For-Geeks/Machine-Learning-Projects#9]
In this Project  I will be  going to implement a predictive model on the Rain Dataset to predict whether it will rain in Australia tomorrow. The dataset contains about 10 years of daily weather observations at various locations in Australia.

**Comment by Sansgupta25** [comment]
Please assign me the above issue for implementing machine learning model .

**Comment by Anjali2201** [comment]
Sure
